#!/bin/bash -x

# Make simlinks/copy files
mkdir ~/.config
mkdir ~/.config/i3
mkdir ~/.config/nvim
mkdir ~/.config/nvim/colors
sudo ln -rsf init.vim ~/.config/nvim/init.vim
sudo ln -rsf .Xresources ~/.Xresources
sudo ln -rsf Xresources-themes ~/.Xresources-themes
sudo ln -rsf begin /bin/begin
sudo ln -rsf darcula.vim ~/.config/nvim/colors
sudo ln -rsf i3/config ~/.config/i3
sudo ln -rsf i3/vol /bin/vol
sudo mkdir /mnt/c/autohot
sudo cp windows-ctrl.ahk /mnt/c/autohot/
sudo chmod a+x /bin/begin
sudo chmod a+x /bin/vol

# Get all the apt packages we'll need
sudo apt-get --assume-yes install curl
sudo apt-get --assume-yes install software-properties-common
sudo apt-add-repository ppa:neovim-ppa/stable
sudo apt-get --assume-yes update

sudo apt-get --assume-yes install python-dev python-pip python3-dev python3-pip python3
sudo apt-get --assume-yes install unzip cargo rlwrap gcc git openjdk-8-jdk grep byobu glances 

sudo apt-get --assume-yes install neovim
sudo apt-get --assume-yes install leiningen 

sudo apt-get --assume-yes install npm

sudo apt-get --assume-yes install xfce4-screenshooter gimp

sudo apt-get --assume-yes install build-essential cmake python3-dev

sudo npm install -g simple-autoreload-server
# Install the rust compiler, which is a dependency for the best parinfer vim plugin on the market
# Uncommont the following line if "cargo" didn't install via apt-get 
# curl https://sh.rustup.rs -sSf | sh

# Install the clojure CLI tools
curl -O https://download.clojure.org/install/linux-install-1.9.0.391.sh
sudo chmod +x linux-install-1.9.0.391.sh
sudo ./linux-install-1.9.0.391.sh
sudo rm linux-install-1.9.0.391.sh

# Make neovim the default, and install plugins 
bash zaph-map-nvim
bash zaph-install-plugins

