#!/bin/bash -x

# Make simlinks/copy files
sudo ln -rsf .vimrc ~/.config/nvim/.vimrc
sudo ln -rsf .Xresources ~/.Xresources
sudo ln -rsf Xresources-themes ~/.Xresources-themes
sudo ln -rsf begin /bin/begin
sudo cp windows-ctrl.ahk /mnt/c/autohot/
sudo chmod a+x /bin/begin

# Get all the apt packages we'll need
sudo apt-get --assume-yes install software-properties-common
sudo apt-add-repository --assume-yes ppa:neovim-ppa/stable
sudo apt-get --assume-yes update

sudo apt-get --assume-yes install python-dev python-pip python3-dev python3-pip python3
sudo apt-get --assume-yes install unzip cargo rlwrap gcc git openjdk-8-jdk grep byobu glances 

sudo apt-get --assume-yes neovim
sudo apt-get --assume-yes leiningen 

# Install the rust compiler, which is a dependency for the best parinfer vim plugin on the market
# Uncommont the following line if "cargo" didn't install via apt-get 
# curl https://sh.rustup.rs -sSf | sh

# Install the clojure CLI tools
curl -O https://download.clojure.org/install/linux-install-1.9.0.391.sh
sudo chmod +x linux-install-1.9.0.391.sh
sudo ./linux-install-1.9.0.391.sh
sudo rm linux-install-1.9.0.391.sh

# Install plugins with vundle
git clone https://github.com/VundleVim/Vundle.vim.git ~/.config/nvim/bundle/Vundle.vim
sudo update-alternatives --install /usr/bin/vi vi /usr/bin/nvim 60
sudo update-alternatives --config vi
sudo update-alternatives --install /usr/bin/vim vi /usr/bin/nvim 60
sudo update-alternatives --config vim
sudo update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 60
sudo update-alternatives --config editor
vim +PluginInstall +qall

# Build parinfer-rust
cd ~/.vim/bundle/parinfer-rust
sudo cargo build --release
cd ~/dotfiles

